sudo: required
language: cpp
services:
  - docker
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - gcc-4.8
    - g++-4.8
    - cmake
    - cmake-data
    - protobuf-compiler
script: cd 3rd/protobuf/cmake && cmake --version && cmake -Dprotobuf_BUILD_TESTS=OFF . && make && cd ../../../ && cmake . && make
